# -*- coding: utf-8 -*-
"""bj10757.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTmxQ90GL3sJgBPaC1yGRvU3mn9l4-IH
"""

# no.10757 큰 수 A+B

a, b = map(int, input().split())

print(a+b)