# -*- coding: utf-8 -*-
"""bj10872.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110gsiu5q16vM3xv-sNcyI9Z9AD0QUoF4
"""

# no.10872 팩토리얼

# 재귀로 풀이
def fac(x):
    if x > 1:
        return x * fac(x-1)
    else:
        return 1

N = int(input())
print(fac(N))

# 단순 for문
N = int(input())
sol = 1
if N == 0:
    print(sol)
else:
    for i in range(1,N+1):
        sol *= i
    print(sol)