# -*- coding: utf-8 -*-
"""bj10926.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTKu1r-P5xz7rqlJkJMSZjef-3CVsKK4
"""

# 10926 ??!

print(input()+'??!')