# -*- coding: utf-8 -*-
"""bj10996.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYKIjLMNrlCAXYP4DwY--pyPF5qLqBTS
"""

# no.10996 별찍기 - 21

N = int(input())

for _ in range(N):
    if N % 2:
        print("*")
    print("* "*(N // 2)) 
    print(" *"*(N // 2))