# -*- coding: utf-8 -*-
"""bj10815.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Reh0HzcG3G7UqQ58HF5iCb10edkx9jUc
"""

# no.10815 숫자 카드

N = int(input())
n = set(map(int, input().split()))
M = int(input())
m = list(map(int, input().split()))

for x in m:
    if x in n:
        print(1, end=' ')
    else:
        print(0, end=' ')