# -*- coding: utf-8 -*-
"""bj1094.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJgKBKn23nk_M8pqE9ryOk0KyMMVS3pw
"""

# no.1094 막대기

X = bin(int(input()))

sol = 0
for x in X[2:]:
    sol += int(x)
print(sol)