# -*- coding: utf-8 -*-
"""bj11724.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sS44M9tIjzGMpgsAMpR71Aw74nCcIKDt
"""

# no.11724 연결 요소의 개수

import sys

def find_connected_component(graph):
    visited = set()
    numList = []

    for vtx in graph:
        if vtx not in visited:
            num = dfs_cc(graph, [], vtx, visited)
            numList.append(num)

    return numList

def dfs_cc(graph, num, vertex, visited):
    if vertex not in visited:
        visited.add(vertex)
        num.append(vertex)
        nbr = graph[vertex] - visited
        for v in nbr:
            dfs_cc(graph, num, v, visited)
    return num

N, M = map(int, input().split())

L = [[] for i in range(N)]

for _ in range(M):
    n, m = map(int, sys.stdin.readline().split())
    L[n-1].append(m)
    L[m-1].append(n)

graph = dict()

for i in range(1, N+1):
    # idx = str(i)
    graph[i] = set(L[i-1])

comp = find_connected_component(graph)

print(len(comp))