# -*- coding: utf-8 -*-
"""bj1152.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o6dJ4iiOIgB2CyunCSjTlw9ZQwOaWm1q
"""

# no.1152 단어의 개수

s = input()
sl = list(s.split())

print(len(sl))