# -*- coding: utf-8 -*-
"""bj11656.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JK8vstdfTLDpqqXV_oQsfhrAYQiZMa7h
"""

# no.11656 접미사 배열

S = input()

L = []

for i in range(len(S)):
    L.append(S[i:])

L.sort()

for x in L:
    print(x)