# -*- coding: utf-8 -*-
"""bj11655.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bio-9CvPiHydf1cz49gXhphp_WMKmA-9
"""

# no.11655 ROT13

S = input()

for x in S:
    if 65 <= ord(x) <= 90:
        tmp = (ord(x) + 13)
        if tmp > 90:
            tmp -= 26
    elif 97 <= ord(x) <= 122:
        tmp = (ord(x) + 13)
        if tmp > 122:
            tmp -= 26
    else:
        tmp = ord(x)
    print(chr(tmp), end='')