# -*- coding: utf-8 -*-
"""bj11654.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVym5zOoM7CMqxK6ijjOZr7ujBBPYraP
"""

# no.11654 아스키코드

c = input()

print(ord(c))