# -*- coding: utf-8 -*-
"""bj1343.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yEdfSggg4Dk_Q0GWJIqwTpy_l4QEGsv
"""

# no.2776 암기왕
T = int(input())

for _ in range(T):
    N = int(input())
    n = list(map(int, input().split()))

    M = int(input())
    m = list(map(int, input().split()))

    for x in m:
        if x in n:
            print(1)
        else:
            print(0)

# 이분탐색

import sys

T = int(sys.stdin.readline())

def binary_search(target, data):
    start = 0
    end = len(data) - 1

    while start <= end:
        mid = (start + end) // 2

        if data[mid] == target:
            return 1
        elif data[mid] < target:
            start = mid + 1
        else:
            end = mid -1

    return 0

for _ in range(T):
    N = int(sys.stdin.readline())
    n = list(map(int, sys.stdin.readline().split()))
    n.sort()

    M = int(sys.stdin.readline())
    m = list(map(int, sys.stdin.readline().split()))

    for x in m:
        print(binary_search(x, n))

def binary_search(target, data):
    start = 0
    end = len(data) - 1

    while start <= end:
        mid = (start + end) // 2

        if data[mid] == target:
            return 1
        elif data[mid] < target:
            start = mid + 1
        else:
            end = mid -1

    return 0

binary_search(7, [1, 4, 5, 2, 3])