# -*- coding: utf-8 -*-
"""bj14929.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czDT6VvKneoAIF3CLDBakINHkmTu9MEO
"""

# no.14929 귀찮아 (SIB)

n = int(input())

L = list(map(int, input().split()))

sum = 0
sol = 0
mul = []

for x in reversed(L):
    sum += x
    mul.append(sum)

mul.reverse()

for i in range(len(L)-1):
    sol += L[i] * mul[i+1]

print(sol)