# -*- coding: utf-8 -*-
"""bj14425.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtOcfsDvTBbvAmkkqVd2ORT6TxHl_J8_
"""

# no.14425 문자열 집합

N, M = map(int, input().split())

S = set()
sol = 0

for _ in range(N):
    S.add(input())

for _ in range(M):
    tmp = input()
    if tmp in S:
        sol += 1

print(sol)

e = set()
e.add('asdasfas')
e.add('abdvsd')
e