# -*- coding: utf-8 -*-
"""bj1676.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwUBDqUBYU2FvVtRDFmMLhn_gHjpMZeC
"""

# no.1676 팩토리얼 0의 개수
from math import factorial as fr

N = int(input())
n = str(fr(N))
tmp = 0
cnt = 0

for x in range(len(n)):
    tmp -= 1
    if n[tmp] == '0':
        cnt += 1
    else:
        break

print(cnt)

