# -*- coding: utf-8 -*-
"""bj17087.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17WQ4W-_bqm2P_5iQtVzYaN8NqaB0wCb3
"""

# no.17087 숨바꼭질 6
def gcd(a, b):
    while b > 0:
        a, b = b, a % b
    return a

N, S = map(int, input().split())
A = list(map(int, input().split()))
L = []

for x in A:
    L.append(abs(S-x))

sol = L[0]

for x in L[1:]:
    sol = gcd(sol, x)

print(sol)