# -*- coding: utf-8 -*-
"""bj18108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMcg-gEwEiSsveE2lBITxrjHK6kITH1e
"""

# no.18108 1998년생인 내가 태국에서는 2541년생?!

print(int(input()) - 543)