# -*- coding: utf-8 -*-
"""bj1940.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ivjft9gnAsd465L6EtLODCjfGoUiBYZ1
"""

# no.1940 주몽

N = int(input())
M = int(input())

L = set(map(int, input().split()))
cnt = 0

for _ in range(N):
    tmp = L.pop()
    k = M - tmp
    if k in L:
        cnt += 1

print(cnt)

a = set([1,2,3])
len(a)