# -*- coding: utf-8 -*-
"""bj1977.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7rErbNRHfvSJwmvx_OmYCWIKZLPnokA
"""

# no.1977 완전제곱수

square_l = [x ** 2 for x in range(1, 101)]

M = int(input())
N = int(input())
sum = 0
s = 0
tmp = 0

for x in square_l:
    if M <= x <= N:
        sum += x
        if tmp == 0:
            s = x
        tmp = 1

if sum:
    print(sum)            
    print(s)
else:
    print(-1)