# -*- coding: utf-8 -*-
"""bj2108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ddu-jTc9YFIdbkLarXB5rLUnHgIB9O-D
"""

# no.2108
from collections import Counter

N = int(input())
L = []

for _ in range(N):
    tmp = int(input())
    L.append(tmp)

L.sort()
if N == 1:
    print(L[0])
    print(L[0])
    print(L[0])
    print(0)

else:
    # 최빈값
    mo = Counter(L)
    m = mo.most_common()
    if m[0][1] == m[1][1]:
        i=1
        l = [m[0]]
        while 1:
            if m[0][1] == m[i][1]:
                l.append(m[i])
                i += 1
            else:
                break
            if i == N:
                break
        l = sorted(l)
        most = l[1][0]
    else:
        most = m[0][0]
    print(round(sum(L)/N))
    print(L[N//2])
    print(most)
    print(max(L) - min(L))

# 두번째 시도
import statistics as st

N = int(input())
L = []

for _ in range(N):
    L.append(int(input()))

mean = st.mean(L)
median = st.median(L)
mo = st.multimode(L)
mo.sort()

if len(mo) == 1:
    mo = mo[0]
else:
    mo = mo[1]

ran = max(L) - min(L)

print(round(mean))
print(median)
print(mo)
print(ran)

from statistics import multimode