# -*- coding: utf-8 -*-
"""bj23841.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvOCeUjpK-8L5Udk7viHeUVvaTEX1TCF
"""

# no.23841 데칼코마니

N, M = map(int, input().split())

L = []

for _ in range(N):
    L.append(input())

for x in L:
    x = list(x)
    for i in range(M):
        if x[i] != '.':
            x[abs(M-1-i)] = x[i]
    x = ''.join(x)
    print(x)