# -*- coding: utf-8 -*-
"""bj23627.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIXLaY-XmOo_5hFiVYgHBTmQsNTU8Y5i
"""

# 23627 driip

s = input()
try:
    if s[-5:] == 'driip':
        print('cute')
    else:
        print('not cute')
except:
    print('not cute')

a = 'asddriip'

a[-5:]