# -*- coding: utf-8 -*-
"""bj2446.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XbIwX77QbalK4U11E-zQcbRh1Ci_DtL9
"""

# no.2446 별 찍기 - 9

N = int(input())

for i in range(2*N-1, 1, -2):
    print(' '*(N - i//2 - 1) + '*'*i)

for i in range(1, 2*N+1, 2):
    print(' '*(N - i//2 - 1) + '*'*i)