# -*- coding: utf-8 -*-
"""bj25083.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-uzm3xUvjtIFqlTiFJTjxBqvU9-g0vBN
"""

# no.25083 새싹

print("         ,r'\"7")
print("r`-_   ,'  ,/")
print(" \\. \". L_r'")
print("   `~\\/")
print("      |")
print("      |")