# -*- coding: utf-8 -*-
"""bj2606.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N97kIDmz6rrNPZjeduuXNzVe8s7yRm2k
"""

# no.2606 바이러스

def find_connected_component(graph):
    visited = set()
    numList = []

    for vtx in graph:
        if vtx not in visited:
            num = dfs_cc(graph, [], vtx, visited)
            numList.append(num)

    return numList

def dfs_cc(graph, num, vertex, visited):
    if vertex not in visited:
        visited.add(vertex)
        num.append(vertex)
        nbr = graph[vertex] - visited
        for v in nbr:
            dfs_cc(graph, num, v, visited)
    return num

N = int(input())
M = int(input())

L = [[] for i in range(N)]

for _ in range(M):
    n, m = map(int, input().split())
    L[n-1].append(m)
    L[m-1].append(n)

graph = dict()

for i in range(1, N+1):
    # idx = str(i)
    graph[i] = set(L[i-1])

comp = find_connected_component(graph)

for x in comp:
    if 1 in x:
        print(len(x) - 1)
        break