# -*- coding: utf-8 -*-
"""bj2776_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xSAPn4XDo3OzbmaXMkeAZMgaO_-xNcj
"""

# no.2776 암기왕

T = int(input())

for _ in range(T):
    N = input()
    n = set(map(int, input().split()))
    M = input()
    m = list(map(int, input().split()))

    for x in m:
        if x in n:
            print(1)
        else:
            print(0)

## 기존 binary search를 사용한 것보다 set을 사용한게
## 두배정도 빠른 속도를 보여줌