# -*- coding: utf-8 -*-
"""bj2839-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dye6ePXh6jdd03k4PmnxYpNUb52kZOA4
"""

# no.2839 설탕 배달

N = int(input())

n = 0
sol = N // 5
tmp = N % 5
for i in range(1, N // 5 + 1):
    if tmp % 3 != 0:
        sol = N // 5 - i
        tmp = N - sol * 5
    else:
        print(sol + tmp // 3)
        n = 1
        break

if n == 0:
    if N % 3 == 0:
        print(N // 3)
    else:
        print(-1)

