# -*- coding: utf-8 -*-
"""bj2908.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXASLnOV9SbDicB6SJxKjos5uBQGP9Xw
"""

# no.2908 상수

a, b = map(int, input().split())

an = (a%10) * 100 + (a%100 - a%10) + (a//100)
bn = (b%10) * 100 + (b%100 - b%10) + (b//100)

if an > bn:
    print(an)
else:
    print(bn)