# -*- coding: utf-8 -*-
"""bj2960.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12y6S5tpGbZ5MCd8u4KXlzUCljxWvG_GH
"""

# no.2960 에라토스테네스의 체

N, K = map(int, input().split())

prime = list(range(2, N+1))
sol = 0
cnt = 0
b = 0

for _ in range(N):
    p = prime[0]
    tmp = p
    i = 1

    while tmp <= N:
        tmp = p * i
        if tmp in prime:
            prime.remove(tmp)
            cnt += 1
            if cnt == K:
                b = 1
                print(tmp)
                break
        i += 1
    
    if b == 1:
        break