# -*- coding: utf-8 -*-
"""bj6571.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11p3UKQ02taMzG1YwDGlmOzaTdY-K3x8U
"""

# no.6571 피보나치 수의 개수

f_l = [1, 2]

for i in range(500):
    a = f_l[i]
    b = f_l[i+1]
    a, b = b, a+b
    f_l.append(b)

s, e = map(int, input().split())
while s or e:
    cnt = 0
    for x in f_l:
        if s <= x <= e:
            cnt += 1
    print(cnt)
    s, e = map(int, input().split())

len(str(f_l[-1]))
f_l[:10]