# -*- coding: utf-8 -*-
"""bj8949.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hrw_EeJbovuPW15SfP7gUX3ZOUbGwqRQ
"""

# no.8949 대충 더해

a, b = map(int, input().split())

A = [x for x in str(a)]
B = [x for x in str(b)]

sol = ''

if len(A) > len(B):
    sol += ''.join(A[:len(A)-len(B)])
    A_ = A[len(A)-len(B):]
    for i in range(len(B)):
        sol += str(int(A_[i]) + int(B[i]))
    print(sol)

elif len(A) < len(B):
    A, B = B, A
    sol += ''.join(A[:len(A)-len(B)])
    A_ = A[len(A)-len(B):]
    for i in range(len(B)):
        sol += str(int(A_[i]) + int(B[i]))
    print(sol)
else:
    for i in range(len(B)):
        sol += str(int(A[i]) + int(B[i]))
    print(sol)

g = ['1', '2', '3']
''.join(g)